export const communityBuilders = [
	{
		name: 'Ivy Walobwa',
		role: 'Community Organizer',
		hobbies: ['hiking'],
		img: '/wtd-kenya-website/public/profile_images/ivy_walobwa.jpg/',
		LinkedIn: 'https://www.linkedin.com/in/ivywalobwa/',
		email: 'ivywalobwa@gmail.com',
		github: '',
		twitter: '',
		blogs: [],
	},
	{
		name: 'Esther Wavinya',
		role: 'Community Co-organizer',
		hobbies: ['Hiking', 'Dancing'],
		img: '/wtd-kenya-website/public/profile_images/esther_wavinya.jpeg',
		LinkedIn: 'https://www.linkedin.com/in/esther-ndavi-5a4b3214b/',
		email: 'estherwavinya80@gmail.com',
		github: '',
		twitter: '',
		blogs: [],
	},
	{
		name: 'Andrew Mukare',
		role: 'Community Volunteer',
		hobbies: ['Cooking', 'Guitar', 'Gaming'],
		img: '/wtd-kenya-website/public/profile_images/andrew_mukare.jpg/',
		LinkedIn: 'https://www.linkedin.com/mwlite/in/andrew-mukare-385088147',
		email: 'dremukare@gmail.com',
		github: 'https://github.com/DreMukare',
		twitter: 'https://twitter.com/MukareAndrew',
		blogs: [],
	},
	{
		name: 'Valentine Gatwiri',
		role: 'Community Volunteer',
		hobbies: ['Stargazing', 'Hiking'],
		img: '/wtd-kenya-website/public/profile_images/valentine_gatwiri.jpeg',
		LinkedIn: '',
		email: '',
		github: '',
		twitter: '',
		blogs: [],
	},
	{
		name: 'Sharon Jebitok',
		role: 'Community Volunteer',
		hobbies: ['African music', 'Learning blockchain development'],
		img: '/wtd-kenya-website/public/profile_images/sharon_jebitok.jpg/',
		LinkedIn: 'LinkedIn.com/in/sharon-jebitok/',
		email: 'sharonkosgei4@gmail.com',
		github: '',
		twitter: '',
		blogs: [],
	},
	{
		name: 'Guantai Nicholas',
		role: 'Community Volunteer',
		hobbies: ['Playing piano', 'Reading', 'Watching movies'],
		img: '/wtd-kenya-website/public/profile_images/guantai_nicholas.jpg/',
		LinkedIn: 'https://www.linkedin.com/in/nicholasguantai/',
		email: 'nicholasguantai528@gmail.com',
		github: '',
		twitter: '',
		blogs: [],
	},
	{
		name: 'Clifford Ouma',
		role: 'Community volunteer',
		hobbies: ['Watching movies'],
		img: '/wtd-kenya-website/public/profile_images/clifford_ouma.jpg/',
		LinkedIn: 'https://www.linkedin.com/in/clifford-ochieng/',
		email: 'ochiengclifford2000@gmail.com',
		github: '',
		twitter: '',
		blogs: [],
	},
	{
		name: 'Collins Jumah',
		role: 'Community Volunteer',
		hobbies: [],
		img: '/wtd-kenya-website/public/profile_images/collins_jumah.jpeg',
		LinkedIn: '',
		email: 'collynejumah2010@gmail.com',
		github: '',
		twitter: '',
		blogs: [],
	},
];
